import type { BootstrapPayload, Match, MatchDetailPayload } from '@/lib/copilot-types'

const fallbackLiveMatches: Match[] = [
  {
    id: 'laliga-elclasico-live',
    homeTeam: 'Real Madrid',
    awayTeam: 'Barcelona',
    homeCode: 'RMA',
    awayCode: 'BAR',
    homeScore: 2,
    awayScore: 1,
    minute: 78,
    periodLabel: '2º Tempo',
    status: 'live',
    league: 'La Liga',
    leagueSlug: 'laliga',
    leagueIcon: '🇪🇸',
    homeOdds: 1.62,
    drawOdds: 4.1,
    awayOdds: 5.5,
    insight: 'Mandante sustenta pressão e controla os espaços',
    insightType: 'positive',
    momentum: 'home',
    coverage: 'premium',
    source: 'fallback_front_demo',
    isSelected: true,
  },
  {
    id: 'bundesliga-leverkusen-live',
    homeTeam: 'Bayer Leverkusen',
    awayTeam: 'RB Leipzig',
    homeCode: 'B04',
    awayCode: 'RBL',
    homeScore: 2,
    awayScore: 2,
    minute: 67,
    periodLabel: '2º Tempo',
    status: 'live',
    league: 'Bundesliga',
    leagueSlug: 'bundesliga',
    leagueIcon: '🇩🇪',
    homeOdds: 2.02,
    drawOdds: 3.55,
    awayOdds: 3.4,
    insight: 'Jogo acelera e risco de gol voltou a subir',
    insightType: 'warning',
    momentum: 'home',
    coverage: 'premium',
    source: 'fallback_front_demo',
  },
]

const fallbackUpcomingMatches: Match[] = [
  {
    id: 'laliga-atletico-upcoming',
    homeTeam: 'Atlético Madrid',
    awayTeam: 'Sevilla',
    homeCode: 'ATM',
    awayCode: 'SEV',
    homeScore: null,
    awayScore: null,
    minute: null,
    periodLabel: null,
    status: 'upcoming',
    kickoff: '16:00',
    kickoffDateLabel: 'Vitrine curada',
    league: 'La Liga',
    leagueSlug: 'laliga',
    leagueIcon: '🇪🇸',
    homeOdds: 1.92,
    drawOdds: 3.25,
    awayOdds: 4.35,
    insight: 'Mando pesa, mas o mercado ainda vê equilíbrio',
    insightType: 'neutral',
    momentum: 'balanced',
    coverage: 'premium',
    source: 'fallback_front_demo',
  },
  {
    id: 'bundesliga-bayern-upcoming',
    homeTeam: 'Bayern Munich',
    awayTeam: 'RB Leipzig',
    homeCode: 'FCB',
    awayCode: 'RBL',
    homeScore: null,
    awayScore: null,
    minute: null,
    periodLabel: null,
    status: 'upcoming',
    kickoff: '18:30',
    kickoffDateLabel: 'Vitrine curada',
    league: 'Bundesliga',
    leagueSlug: 'bundesliga',
    leagueIcon: '🇩🇪',
    homeOdds: 1.7,
    drawOdds: 4.05,
    awayOdds: 4.4,
    insight: 'Bayern Munich larga mais protegido, mas o RB Leipzig tem perfil para agredir em transição',
    insightType: 'warning',
    momentum: 'home',
    coverage: 'premium',
    source: 'fallback_front_demo',
  },
]

const fallbackLiveMatchDetails: Record<string, MatchDetailPayload> = {
  'laliga-elclasico-live': {
    match: fallbackLiveMatches[0],
    headline: {
      title: 'Leitura do Copiloto',
      summary:
        'Real Madrid chega mais inteiro ao momento atual. A leitura combina vantagem no placar, controle territorial e mercado ainda precificando o jogo como vivo.',
      confidence: 'alta',
      volatility: 'média',
      updatedLabel: 'ATUALIZADO',
    },
    livePulse: {
      summary: 'Na última janela, o Real Madrid encurtou o preço do 1 e voltou a empurrar o jogo com mais campo ofensivo.',
      windowLabel: '8 min',
      snapshotCount: 4,
      startMinute: 70,
      endMinute: 78,
      scoreShift: '1-1 -> 2-1',
      marketShift: '1.95 -> 1.62 no 1',
      pressureShift: '14-11 -> 22-13 perigo',
      drivers: [
        'Placar saiu de 1-1 para 2-1.',
        'Odd do 1 foi de 1.95 para 1.62.',
        'Ataques perigosos cresceram para 22-13.',
      ],
      metrics: [
        { label: 'Resultado', value: '+11 pts', tone: 'positive' },
        { label: 'Mercado 1', value: '-0.33', tone: 'warning' },
        { label: 'Pressão', value: '+10 perigo', tone: 'positive' },
        { label: 'No alvo', value: '+2', tone: 'positive' },
      ],
    },
    scenarios: [
      {
        id: 'result',
        title: 'Resultado Final',
        probability: 67,
        confidence: 'alta',
        trend: 'up',
        description: 'Real Madrid lidera a leitura de resultado. Mercado, momento e controle territorial sustentam o cenário.',
        drivers: [
          'Mandante vence a probabilidade implícita atual do 1X2',
          'Barcelona ainda precisa se expor na reta final',
          'Vantagem no placar mantém o cenário protegido',
          'Momento recente pesa para o lado da casa',
        ],
        change: 11,
        changeLabel: '+11 pts · 8 min',
      },
      {
        id: 'goals',
        title: 'Cenário de Gols',
        probability: 78,
        confidence: 'alta',
        trend: 'up',
        description: 'A dinâmica atual favorece pelo menos mais uma chegada clara e mantém o total de gols sensível até o fim.',
        drivers: [
          'Placar em 2-1 já pressiona a linha de total',
          'Partida entrou em zona de transição e risco alto',
          'Mercado de over encurtou no segundo tempo',
          'Volatilidade segue alta na faixa final',
        ],
        change: 8,
        changeLabel: '+8 pts · 8 min',
      },
      {
        id: 'momentum',
        title: 'Momento & Risco',
        probability: 71,
        confidence: 'alta',
        trend: 'stable',
        description: 'O risco de gol nos próximos 10 minutos ainda favorece o mandante, mas o visitante segue perigoso se recuperar a segunda bola.',
        drivers: [
          'Real Madrid controla melhor a profundidade agora',
          'Barcelona continua atacando com linha alta',
          'Mudança de cenário segue possível com uma finalização grande',
          'Jogo permanece vivo para atualização rápida',
        ],
        change: 6,
        changeLabel: '+6 pts · 8 min',
      },
    ],
    timeline: [
      {
        id: 'goal-1',
        minute: 13,
        type: 'goal',
        title: 'Gol do Real Madrid',
        description: 'Mandante abriu o placar em transição rápida',
        team: 'home',
        impact: 'high',
      },
      {
        id: 'goal-2',
        minute: 28,
        type: 'goal',
        title: 'Gol do Barcelona',
        description: 'Visitante empatou em jogada apoiada pela esquerda',
        team: 'away',
        impact: 'high',
      },
      {
        id: 'insight-1',
        minute: 46,
        type: 'insight',
        title: 'Cenário recalibrado',
        description: 'O equilíbrio de mercado diminuiu e o mandante voltou a liderar o contexto.',
        impact: 'medium',
      },
      {
        id: 'goal-3',
        minute: 61,
        type: 'goal',
        title: 'Gol do Real Madrid',
        description: 'A vantagem voltou para o lado da casa após ataque vertical.',
        team: 'home',
        impact: 'high',
      },
      {
        id: 'momentum-1',
        minute: 78,
        type: 'momentum',
        title: 'Pressão do mandante',
        description: 'Real Madrid sustenta campo ofensivo e não deixa o adversário respirar.',
        team: 'home',
        impact: 'high',
      },
    ],
    homeStats: {
      attack: 86,
      defense: 78,
      form: 84,
      pressure: 74,
      control: 88,
      danger: 83,
    },
    awayStats: {
      attack: 84,
      defense: 72,
      form: 77,
      pressure: 69,
      control: 80,
      danger: 79,
    },
    relatedMarkets: [
      { name: 'Próximo gol - RMA', odds: 1.42, trend: 'hot' },
      { name: 'Over 2.5 gols', odds: 1.2, trend: 'up' },
      { name: 'Ambas marcam - Sim', odds: 1.18, trend: 'stable' },
      { name: 'RMA vence 2º tempo', odds: 2.05, trend: 'up' },
      { name: 'Total cantos Over 9.5', odds: 1.88, trend: 'stable' },
    ],
    recentForm: {
      home: ['W', 'W', 'D', 'W', 'W'],
      away: ['W', 'D', 'W', 'W', 'L'],
    },
    h2hHistory: {
      homeWins: 1,
      draws: 0,
      awayWins: 1,
      lastFive: [
        { homeTeam: 'Real Madrid', awayTeam: 'Barcelona', home: 2, away: 1, date: '10/04/2021' },
        { homeTeam: 'Barcelona', awayTeam: 'Real Madrid', home: 1, away: 3, date: '24/10/2020' },
      ],
    },
    keyPlayers: [
      { name: 'Kylian Mbappé', team: 'home', status: 'Em campo', impact: '23 gols, 4 assistências' },
      { name: 'Vinicius Junior', team: 'home', status: 'Em campo', impact: '16 gols, 7 assistências' },
      { name: 'Robert Lewandowski', team: 'away', status: 'Em campo', impact: '20 gols, 2 assistências' },
      { name: 'Lamine Yamal', team: 'away', status: 'Banco', impact: '10 gols, 12 assistências' },
    ],
    leagueContext: {
      homePosition: 2,
      awayPosition: 3,
      homePoints: 81,
      awayPoints: 76,
      matchday: 30,
      totalMatchdays: 38,
      homeGoalDiff: '+35',
      awayGoalDiff: '+42',
    },
    monitoring: [
      {
        kind: 'insight',
        text: 'Se o Real Madrid mantiver a ocupação do terço final por mais 5 minutos, a leitura principal pode passar de 70%.',
      },
      {
        kind: 'watch',
        text: 'Observe a faixa entre 78’ e 88’: é o trecho com maior sensibilidade de mudança neste jogo.',
      },
    ],
  },
  'bundesliga-leverkusen-live': {
    match: fallbackLiveMatches[1],
    headline: {
      title: 'Leitura do Copiloto',
      summary:
        'Bayer Leverkusen acelera a partida no segundo tempo. O contexto ainda está aberto, mas o mandante empurra mais o jogo e o cenário de próximo gol segue aquecido.',
      confidence: 'média',
      volatility: 'alta',
      updatedLabel: 'ATUALIZADO',
    },
    livePulse: {
      summary: 'A última janela mostrou jogo ainda mais aberto, com mercado e pressão empurrando o risco de novo gol.',
      windowLabel: '6 min',
      snapshotCount: 3,
      startMinute: 61,
      endMinute: 67,
      scoreShift: '2-2 -> 2-2',
      marketShift: '2.24 -> 2.02 no 1',
      pressureShift: '18-15 -> 26-19 perigo',
      drivers: [
        'Odd do 1 encurtou de 2.24 para 2.02.',
        'Ataques perigosos cresceram para 26-19.',
        'O cenário de gols ganhou mais tração na janela.',
      ],
      metrics: [
        { label: 'Resultado', value: '+4 pts', tone: 'positive' },
        { label: 'Mercado 1', value: '-0.22', tone: 'warning' },
        { label: 'Pressão', value: '+12 perigo', tone: 'positive' },
        { label: 'No alvo', value: '+2', tone: 'positive' },
      ],
    },
    scenarios: [
      {
        id: 'result',
        title: 'Resultado Final',
        probability: 52,
        confidence: 'média',
        trend: 'up',
        description: 'Leverkusen lidera por pouco a leitura de resultado, mas o empate ainda mantém o jogo em zona volátil.',
        drivers: [
          'Mercado segue apertado, mas com leve viés para o mandante',
          'Leverkusen chega em momento mais estável',
          'RB Leipzig ainda cria perigo em transição',
          'Qualquer gol muda o jogo e recalibra tudo',
        ],
        change: 4,
        changeLabel: '+4 pts · 6 min',
      },
      {
        id: 'goals',
        title: 'Cenário de Gols',
        probability: 82,
        confidence: 'alta',
        trend: 'up',
        description: 'A dinâmica atual favorece mais um gol antes do fim. O jogo continua acelerado e com poucos sinais de acomodação.',
        drivers: [
          'Placar em 2-2 deixa o total em zona crítica',
          'As duas equipes seguem atacando espaços',
          'Mercado de over está comprimido',
          'Volatilidade está acima do padrão da rodada',
        ],
        change: 9,
        changeLabel: '+9 pts · 6 min',
      },
      {
        id: 'momentum',
        title: 'Momento & Risco',
        probability: 69,
        confidence: 'alta',
        trend: 'up',
        description: 'O risco de gol nos próximos 10 minutos favorece o mandante, com o visitante ainda ameaçando em transição curta.',
        drivers: [
          'Leverkusen recuperou territorialidade',
          'Jogo com troca rápida de posse',
          'Linha defensiva visitante segue exposta',
          'Mudança de cenário pode acontecer com uma única chegada limpa',
        ],
        change: 7,
        changeLabel: '+7 pts · 6 min',
      },
    ],
    timeline: [
      {
        id: 'bund-goal-1',
        minute: 24,
        type: 'goal',
        title: 'Gol do Bayer Leverkusen',
        description: 'Mandante achou o espaço após bola longa',
        team: 'home',
        impact: 'high',
      },
      {
        id: 'bund-goal-2',
        minute: 32,
        type: 'goal',
        title: 'Gol do RB Leipzig',
        description: 'Visitante empatou em transição curta',
        team: 'away',
        impact: 'high',
      },
      {
        id: 'bund-insight-1',
        minute: 48,
        type: 'insight',
        title: 'Cenário recalibrado',
        description: 'O jogo voltou a abrir e a linha de gols subiu com força.',
        impact: 'medium',
      },
      {
        id: 'bund-goal-3',
        minute: 56,
        type: 'goal',
        title: 'Gol do RB Leipzig',
        description: 'Visitante virou o placar e aumentou a volatilidade.',
        team: 'away',
        impact: 'high',
      },
      {
        id: 'bund-momentum-1',
        minute: 67,
        type: 'momentum',
        title: 'Pressão do mandante',
        description: 'Leverkusen voltou a empurrar o jogo e aumentou o risco de novo gol.',
        team: 'home',
        impact: 'high',
      },
    ],
    homeStats: {
      attack: 88,
      defense: 80,
      form: 91,
      pressure: 82,
      control: 79,
      danger: 86,
    },
    awayStats: {
      attack: 79,
      defense: 71,
      form: 73,
      pressure: 76,
      control: 70,
      danger: 77,
    },
    relatedMarkets: [
      { name: 'Próximo gol - B04', odds: 1.82, trend: 'hot' },
      { name: 'Over 3.5 gols', odds: 1.4, trend: 'up' },
      { name: 'Ambas marcam - Sim', odds: 1.12, trend: 'stable' },
      { name: 'B04 vence 2º tempo', odds: 2.15, trend: 'up' },
      { name: 'Total cantos Over 10.5', odds: 1.96, trend: 'stable' },
    ],
    recentForm: {
      home: ['W', 'W', 'W', 'D', 'W'],
      away: ['W', 'L', 'W', 'W', 'D'],
    },
    h2hHistory: {
      homeWins: 1,
      draws: 0,
      awayWins: 1,
      lastFive: [
        { homeTeam: 'RB Leipzig', awayTeam: 'Bayer Leverkusen', home: 2, away: 3, date: '20/01/2024' },
        { homeTeam: 'Bayer Leverkusen', awayTeam: 'RB Leipzig', home: 3, away: 2, date: '19/08/2023' },
      ],
    },
    keyPlayers: [
      { name: 'Patrik Schick', team: 'home', status: 'Em campo', impact: '17 gols, 0 assistências' },
      { name: 'Florian Wirtz', team: 'home', status: 'Em campo', impact: '10 gols, 10 assistências' },
      { name: 'Benjamin Šeško', team: 'away', status: 'Em campo', impact: '13 gols, 5 assistências' },
      { name: 'Xavi Simons', team: 'away', status: 'Banco', impact: '9 gols, 5 assistências' },
    ],
    leagueContext: {
      homePosition: 1,
      awayPosition: 4,
      homePoints: 87,
      awayPoints: 63,
      matchday: 22,
      totalMatchdays: 34,
      homeGoalDiff: '+56',
      awayGoalDiff: '+31',
    },
    monitoring: [
      {
        kind: 'insight',
        text: 'Se Leverkusen mantiver o volume ofensivo até a faixa dos 75’, a leitura de próximo gol pode subir acima de 75%.',
      },
      {
        kind: 'watch',
        text: 'Observe a transição defensiva do visitante entre 67’ e 79’: é onde o jogo está mais vulnerável.',
      },
    ],
  },
}

const fallbackUpcomingDetails: Record<string, MatchDetailPayload> = {
  'laliga-atletico-upcoming': {
    match: fallbackUpcomingMatches[0],
    headline: {
      title: 'Leitura do Copiloto',
      summary:
        'Atlético Madrid entra melhor precificado e com mando favorável. O cenário é de controle maior do mandante, mas com visitante capaz de alongar o jogo se resistir ao início.',
      confidence: 'média',
      volatility: 'baixa',
      updatedLabel: 'PRÉ-JOGO',
    },
    scenarios: [
      {
        id: 'result',
        title: 'Resultado Final',
        probability: 54,
        confidence: 'média',
        trend: 'stable',
        description: 'Atlético Madrid abre o cenário de resultado com vantagem moderada.',
        drivers: ['Mando forte', 'Mercado ainda equilibrado', 'Diferença de força recente aparece a favor do mandante'],
      },
      {
        id: 'goals',
        title: 'Cenário de Gols',
        probability: 46,
        confidence: 'média',
        trend: 'stable',
        description: 'A linha de gols ainda está presa ao contexto tático mais travado.',
        drivers: ['Jogo com tendência a posse controlada', 'Visitante deve baixar bloco', 'Mercado não comprou over cedo'],
      },
      {
        id: 'momentum',
        title: 'Momento & Risco',
        probability: 41,
        confidence: 'baixa',
        trend: 'stable',
        description: 'O risco imediato depende de como o Atlético vai acelerar o primeiro quarto de jogo.',
        drivers: ['Primeiros 15 minutos serão chave', 'Pressão inicial do mandante pode ditar tom', 'Visitante deve proteger área primeiro'],
      },
    ],
    timeline: [],
    homeStats: {
      attack: 74,
      defense: 81,
      form: 76,
      pressure: 67,
      control: 71,
      danger: 70,
    },
    awayStats: {
      attack: 66,
      defense: 64,
      form: 58,
      pressure: 59,
      control: 61,
      danger: 57,
    },
    relatedMarkets: [
      { name: 'Atlético vence', odds: 1.92, trend: 'up' },
      { name: 'Under 2.5 gols', odds: 1.74, trend: 'stable' },
      { name: 'Ambas marcam - Não', odds: 1.82, trend: 'stable' },
    ],
    recentForm: {
      home: ['W', 'D', 'W', 'W', 'L'],
      away: ['D', 'L', 'W', 'D', 'W'],
    },
    h2hHistory: {
      homeWins: 0,
      draws: 0,
      awayWins: 0,
      lastFive: [],
    },
    keyPlayers: [
      { name: 'Julián Alvarez', team: 'home', status: 'Provável titular', impact: '7 gols, 2 assistências' },
      { name: 'Antoine Griezmann', team: 'home', status: 'Provável titular', impact: '5 gols, 3 assistências' },
      { name: 'Dodi Lukebakio', team: 'away', status: 'Provável titular', impact: '11 gols, 2 assistências' },
      { name: 'Isaac Romero', team: 'away', status: 'Opção', impact: '4 gols, 2 assistências' },
    ],
    leagueContext: {
      homePosition: 4,
      awayPosition: 8,
      homePoints: 64,
      awayPoints: 48,
      matchday: 31,
      totalMatchdays: 38,
      homeGoalDiff: '+19',
      awayGoalDiff: '+4',
    },
    monitoring: [
      { kind: 'insight', text: 'Observe como o Atlético inicia o jogo: domínio inicial fortalece muito o cenário do mandante.' },
      { kind: 'watch', text: 'Se o Sevilla resistir à primeira pressão, a probabilidade de empate ganha valor tático.' },
    ],
  },
  'bundesliga-bayern-upcoming': {
    match: fallbackUpcomingMatches[1],
    headline: {
      title: 'Leitura do Copiloto',
      summary:
        'Bayern Munich entra na frente no pré-jogo por força ofensiva e preço de mercado, mas o RB Leipzig tem repertório suficiente para manter o jogo vivo.',
      confidence: 'média',
      volatility: 'baixa',
      updatedLabel: 'PRÉ-JOGO',
    },
    scenarios: [
      {
        id: 'result',
        title: 'Resultado Final',
        probability: 58,
        confidence: 'média',
        trend: 'stable',
        description: 'Bayern Munich abre a leitura de resultado com margem saudável.',
        drivers: ['Mercado ainda dá preço forte ao mandante', 'Ataque do Bayern segue acima da média', 'Leipzig continua perigoso em transição'],
      },
      {
        id: 'goals',
        title: 'Cenário de Gols',
        probability: 64,
        confidence: 'alta',
        trend: 'up',
        description: 'É um jogo naturalmente mais inclinado a gols do que a contenção.',
        drivers: ['Perfil ofensivo dos dois lados', 'Mercado compra over cedo', 'Espaços tendem a aparecer'],
      },
      {
        id: 'momentum',
        title: 'Momento & Risco',
        probability: 44,
        confidence: 'média',
        trend: 'stable',
        description: 'A primeira leitura ao vivo vai depender de quem assumir o campo nos 15 minutos iniciais.',
        drivers: ['Mandante deve empurrar bloco alto', 'Visitante pode responder em contra-ataque', 'Primeira chance clara muda a leitura rápido'],
      },
    ],
    timeline: [],
    homeStats: {
      attack: 90,
      defense: 72,
      form: 82,
      pressure: 75,
      control: 85,
      danger: 89,
    },
    awayStats: {
      attack: 78,
      defense: 68,
      form: 71,
      pressure: 73,
      control: 69,
      danger: 76,
    },
    relatedMarkets: [
      { name: 'Bayern vence', odds: 1.7, trend: 'up' },
      { name: 'Over 2.5 gols', odds: 1.6, trend: 'hot' },
      { name: 'Ambas marcam - Sim', odds: 1.58, trend: 'stable' },
    ],
    recentForm: {
      home: ['W', 'W', 'W', 'D', 'L'],
      away: ['W', 'D', 'L', 'W', 'W'],
    },
    h2hHistory: {
      homeWins: 0,
      draws: 0,
      awayWins: 0,
      lastFive: [],
    },
    keyPlayers: [
      { name: 'Harry Kane', team: 'home', status: 'Provável titular', impact: '18 gols, 5 assistências' },
      { name: 'Jamal Musiala', team: 'home', status: 'Provável titular', impact: '12 gols, 4 assistências' },
      { name: 'Benjamin Šeško', team: 'away', status: 'Provável titular', impact: '13 gols, 5 assistências' },
      { name: 'Xavi Simons', team: 'away', status: 'Provável titular', impact: '9 gols, 5 assistências' },
    ],
    leagueContext: {
      homePosition: 2,
      awayPosition: 4,
      homePoints: 71,
      awayPoints: 59,
      matchday: 23,
      totalMatchdays: 34,
      homeGoalDiff: '+47',
      awayGoalDiff: '+24',
    },
    monitoring: [
      { kind: 'insight', text: 'Se o Bayern assumir posse territorial cedo, a leitura do mandante fica mais forte sem precisar de gol rápido.' },
      { kind: 'watch', text: 'Se o Leipzig encaixar a transição nos primeiros 20 minutos, o cenário de gols ganha força antes do mercado ajustar.' },
    ],
  },
}

export const fallbackMatchDetails: Record<string, MatchDetailPayload> = {
  ...fallbackLiveMatchDetails,
  ...fallbackUpcomingDetails,
}

export const fallbackBootstrap: BootstrapPayload = {
  generatedAt: new Date().toISOString(),
  sourceMode: 'fallback_front_demo',
  supportedLeagues: ['La Liga', 'Bundesliga'],
  selectedMatchId: 'laliga-elclasico-live',
  selectedMatchDetail: fallbackLiveMatchDetails['laliga-elclasico-live'],
  replayCount: 6,
  liveMatches: fallbackLiveMatches,
  upcomingMatches: fallbackUpcomingMatches,
}

export const emptyBootstrap: BootstrapPayload = {
  generatedAt: new Date().toISOString(),
  sourceMode: 'loading',
  supportedLeagues: ['La Liga', 'Bundesliga'],
  selectedMatchId: '',
  selectedMatchDetail: null,
  replayCount: 6,
  liveMatches: [],
  upcomingMatches: [],
}

export const emptyMatchDetail: MatchDetailPayload = {
  match: {
    id: 'loading-match',
    homeTeam: '',
    awayTeam: '',
    homeCode: '',
    awayCode: '',
    homeScore: null,
    awayScore: null,
    minute: null,
    periodLabel: null,
    status: 'upcoming',
    kickoff: null,
    kickoffDateLabel: null,
    league: '',
    leagueSlug: '',
    leagueIcon: '⚽',
    homeOdds: 0,
    drawOdds: 0,
    awayOdds: 0,
    insight: '',
    insightType: 'neutral',
    momentum: 'balanced',
    coverage: 'essencial',
    source: 'loading',
  },
  headline: {
    title: 'Leitura do Copiloto',
    summary: 'Carregando leitura do jogo selecionado.',
    confidence: 'baixa',
    volatility: 'baixa',
    updatedLabel: 'CARREGANDO',
  },
  livePulse: null,
  scenarios: [],
  timeline: [],
  homeStats: {
    attack: 0,
    defense: 0,
    form: 0,
    pressure: 0,
    control: 0,
    danger: 0,
  },
  awayStats: {
    attack: 0,
    defense: 0,
    form: 0,
    pressure: 0,
    control: 0,
    danger: 0,
  },
  relatedMarkets: [],
  recentForm: {
    home: [],
    away: [],
  },
  h2hHistory: {
    homeWins: 0,
    draws: 0,
    awayWins: 0,
    lastFive: [],
  },
  keyPlayers: [],
  leagueContext: {
    homePosition: 0,
    awayPosition: 0,
    homePoints: 0,
    awayPoints: 0,
    matchday: 0,
    totalMatchdays: 0,
    homeGoalDiff: '0',
    awayGoalDiff: '0',
  },
  monitoring: [],
}

export function buildTransientDetail(match: Match): MatchDetailPayload {
  const impliedHome = match.homeOdds > 0 ? 1 / match.homeOdds : 0
  const impliedDraw = match.drawOdds > 0 ? 1 / match.drawOdds : 0
  const impliedAway = match.awayOdds > 0 ? 1 / match.awayOdds : 0
  const total = impliedHome + impliedDraw + impliedAway || 1
  const homeProb = Math.round((impliedHome / total) * 100)
  const drawProb = Math.round((impliedDraw / total) * 100)
  const awayProb = Math.max(1, 100 - homeProb - drawProb)
  const leaderProb = Math.max(homeProb, awayProb)
  const leaderTeam = homeProb >= awayProb ? match.homeTeam : match.awayTeam
  const totalGoals = (match.homeScore ?? 0) + (match.awayScore ?? 0)
  const goalsProb = Math.min(84, 36 + totalGoals * 13 + ((match.minute ?? 0) >= 35 ? 8 : 0))
  const riskProb = Math.min(80, 32 + ((match.minute ?? 0) >= 20 ? 8 : 0) + (match.insightType === 'warning' ? 12 : 0))

  return {
    match,
    headline: {
      title: 'Leitura do Copiloto',
      summary:
        match.status === 'live'
          ? `${leaderTeam} lidera a leitura essencial com base no mercado, no placar atual e no ritmo capturado no card principal.`
          : `${leaderTeam} chega melhor precificado no pré-jogo e sustenta a leitura essencial até a atualização completa da partida.`,
      confidence: match.coverage === 'premium' ? 'média' : 'baixa',
      volatility: match.status === 'live' ? 'média' : 'baixa',
      updatedLabel: match.coverage === 'premium' ? 'LEITURA PREMIUM' : 'LEITURA ESSENCIAL',
    },
    livePulse: null,
    scenarios: [
      {
        id: 'result',
        title: 'Resultado Final',
        probability: leaderProb,
        confidence: match.coverage === 'premium' ? 'média' : 'baixa',
        trend: match.insightType === 'positive' ? 'up' : match.insightType === 'negative' ? 'down' : 'stable',
        description: 'Mercado e estado atual sustentam a leitura principal enquanto a análise completa é recarregada.',
        drivers: [
          `Probabilidades implícitas atuais: ${homeProb}% / ${drawProb}% / ${awayProb}%`,
          match.insight || 'Sem driver adicional nesta janela.',
        ],
      },
      {
        id: 'goals',
        title: 'Cenário de Gols',
        probability: goalsProb,
        confidence: 'baixa',
        trend: totalGoals >= 2 ? 'up' : 'stable',
        description: 'Leitura rápida de gols baseada em placar, minuto e mercado principal.',
        drivers: [
          `Placar atual: ${match.homeScore ?? 0}-${match.awayScore ?? 0}`,
          `Minuto da partida: ${match.minute ?? 0}'`,
        ],
      },
      {
        id: 'momentum',
        title: 'Momento & Risco',
        probability: riskProb,
        confidence: 'baixa',
        trend: match.momentum === 'balanced' ? 'stable' : 'up',
        description: 'Leitura transitória enquanto o detalhe completo do jogo é recomposto.',
        drivers: [
          match.insight || 'Sem ruptura forte no cenário.',
          `Momento atual: ${
            match.momentum === 'home'
              ? match.homeTeam
              : match.momentum === 'away'
              ? match.awayTeam
              : 'jogo equilibrado'
          }.`,
        ],
      },
    ],
    timeline: [],
    homeStats: emptyMatchDetail.homeStats,
    awayStats: emptyMatchDetail.awayStats,
    relatedMarkets: [
      { name: `Vitória ${match.homeCode}`, odds: match.homeOdds, trend: 'up' },
      { name: 'Empate', odds: match.drawOdds, trend: 'stable' },
      { name: `Vitória ${match.awayCode}`, odds: match.awayOdds, trend: 'up' },
    ],
    recentForm: { home: [], away: [] },
    h2hHistory: { homeWins: 0, draws: 0, awayWins: 0, lastFive: [] },
    keyPlayers: [],
    leagueContext: emptyMatchDetail.leagueContext,
    monitoring: [
      {
        kind: 'insight',
        text: 'A leitura completa volta assim que o backend recompuser a partida no feed principal.',
      },
      {
        kind: 'watch',
        text: 'Se o jogo sair da lista ao vivo, a seleção será movida automaticamente para o melhor jogo disponível.',
      },
    ],
  }
}
